// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Username  string
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
