// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package lives

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Life struct {
	Streamid    int32
	Userid      int32
	Title       string
	Description pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
