// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Life struct {
	LiveID      int32
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	StartTime   pgtype.Timestamp
	EndTime     pgtype.Timestamp
	StreamUrl   pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type User struct {
	UserID      pgtype.UUID
	Email       string
	FirstName   pgtype.Text
	LastName    pgtype.Text
	PhoneNumber pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
