// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID   pgtype.UUID
	AccountName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Live struct {
	LiveID                      int32
	AccountID                   pgtype.UUID
	Title                       string
	Description                 pgtype.Text
	StartTime                   pgtype.Timestamp
	EndTime                     pgtype.Timestamp
	ScheduledStartTime          pgtype.Timestamp
	ScheduledEndTime            pgtype.Timestamp
	LiveAppName                 pgtype.Text
	StreamName                  pgtype.Text
	LiveSecretEncrypted         pgtype.Text
	LiveSecretHash              pgtype.Text
	StreamBroadcastUrlEncrypted pgtype.Text
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

type LiveLog struct {
	LiveLogID      int32
	LiveID         pgtype.Int4
	Action         pgtype.Text
	ClientID       pgtype.Text
	StreamID       pgtype.Text
	ServerID       pgtype.Text
	ServiceID      pgtype.Text
	Ip             pgtype.Text
	Vhost          pgtype.Text
	App            pgtype.Text
	Tcurl          pgtype.Text
	StreamUrlParam pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type LiveStat struct {
	LiveStatID int32
	LiveID     pgtype.Int4
	Status     pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	UserID        pgtype.UUID
	FirebaseUid   pgtype.Text
	Email         string
	EmailVerified pgtype.Bool
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DisplayName   pgtype.Text
	PhotoUrl      pgtype.Text
	PhoneNumber   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserAccountRole struct {
	UserID    pgtype.UUID
	AccountID pgtype.UUID
	Role      pgtype.Text
}

type UserInvite struct {
	InviteID     pgtype.UUID
	InvitedBy    pgtype.UUID
	AccountID    pgtype.UUID
	EmailInvited string
	Status       string
}
